version: '3.7'
services:
  nginx:
    container_name: dev_web
    restart: on-failure
    image: nginx:1.21.5
    volumes:
      - ./nginx/prod/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/static
    ports:
      - "80:80"
    depends_on:
      - web
  web:
    container_name: dev_backend
    build: .
    restart: always
    env_file: dev.env
    command: gunicorn djangoProject.wsgi:application --bind 0.0.0.0:8080
    volumes:
     - .:/app
     - static_volume:/app/static
    depends_on:
     - db
    ports:
      - "8080:8080"
  db:
    container_name: dev_db
    image: postgres:14.2-alpine
    env_file: dev.env
    hostname: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    restart: on-failure


volumes:
  static_volume:
  postgres_data: