# Generated by Django 4.0.1 on 2022-01-18 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GithubUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('avatar_url', models.URLField(max_length=255)),
                ('html_url', models.URLField(max_length=255)),
                ('followers', models.IntegerField()),
                ('following', models.IntegerField()),
                ('public_repos', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
    ]
