# Generated by Django 4.0.1 on 2022-01-18 13:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='githubuser',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='githubuser',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='githubuser',
            name='retrieved_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime.now),
            preserve_default=False,
        ),
    ]
