# Generated by Django 4.0.1 on 2022-01-18 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_githubuser_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubuser',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
